
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dados
spec:
  capacity:
    storage: 10gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db
spec:
  resources:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100mi
      storageClassName: mysql-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql-meuBanco
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306

        volumeMounts:
          - mountPath: /var/lib/mysql/
            name: dados
        volumes:
          - name: dados
            persistenceVolumeClaim:
            claimName: dados

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: php-minhaImagem
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80



